### ISSUE TITLE
Cancelling a promise.

### ISSUE THREAD

**Issue by ostryhub** [Real-Serious-Games/C-Sharp-Promise#105]
Hi I have a simple questions - can you cancel a promise ?

Why I am asking:
Say I have a view that when showed asks some resource manager for the list of image promises (through the presenter of some sort...).

I am only interested in promises resolving when the view is active and presented.
Now lets say the view gets hidden before some promises make it back with the images.

Am I able to unregister from those promises "resolvation" or maybe keep the promise reference and cancel it when no longer needed (when the prsenter of the view is notified that its getting hidden).

Is there any way to cancel a scheduled promise ?

Thanks !

**Comment by RoryDungan** [comment]
The library currently has no way to cancel promises. We've based our implementation on [JavaScript promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), which have [no built in function for cancellation](https://medium.com/@benlesh/promise-cancellation-is-dead-long-live-promise-cancellation-c6601f1f5082). That said, some [3rd party JS promise libraries](http://bluebirdjs.com/docs/api/cancellation.html) have added this feature and we aren't opposed to adding our own features on top of the promise spec to this library too as long as it remains compatible with standard promises.

The good thing is that implementing cancellation for a promise yourself isn't too hard. Basically all you'll need to do is store a token somewhere and check it in your promise callback, throwing an exception if it is true.
```cs
bool cancellationToken = false;
var promise = SomeOperationThatTakesTime()
    .Then(url => 
    {
        if (cancellationToken)
        {
            throw new CancelledException();
        }
        return DownloadImage(url);
    })
    .Catch(ex => 
    {
        if (ex is CancelledException)
        {
            Debug.Log("Promise cancelled");
            return;
        }
        throw ex;
    })
    .Done();
cancellationToken = true;
```

Alternatively, if you want a solution that's similar to promises but has cancellation built-in, I'd recommend checking out [Rx Observables](https://github.com/dotnet/reactive). If you're using Unity you can use [UniRx](https://github.com/neuecc/UniRx).

**Comment by IvanMurzak** [comment]
@RoryDungan thanks for the great tool! It works as a charm. Just cancellation would be great to have. I see the point and even technical troubles of making it. 

What about at least an ability to disable calling `.Then` method.
Let's say it is not "Cancellation" but "Ignoring".
Can we `.Ignore` a promise to stop it to run `.Then` method when it is done?

### The purpose of doing that
There is a promise I had been started, and the is `.Then` which will do something when it will be completed. But situation had been changed, and I don't care anymore about executing .Then method. Even more, the execution the `.Then` method in current state would even break the logic. Of course I can construct wrapper and extensions to handle it, but why if that could be natively integrated into the `RSG.IPromise` as an extension method.

**Comment by timcassell** [comment]
This project is no longer maintained (since 6 years ago!). I built an alternative library [ProtoPromise](https://github.com/timcassell/ProtoPromise) that has cancelations built in.
