### ISSUE TITLE
Exceptions in immediately called function?

### ISSUE THREAD

**Issue by mikecann** [Real-Serious-Games/C-Sharp-Promise#18]
Hi,

Suppose we have the following:

```
private IPromise DownloadFile()
{
    return DoAsyncOp1()
        .Then(x => DoAsynOp2())
        .Catch(e => Debugger.Log("Whoopsie!"));
}

private IPromise DoAsyncOp1()
{
    // If we throw an exception here, it wont be caught in the handler above
}

private IPromise DoAsynOp2()
{
    // If we throw an exception here, it WILL be caught in the handler above
}
```

Is the how would you engineer a safe solution to this? Would you do:

```
private IPromise DownloadFile()
{​
    return Promise.Resolve()
        .Then(() => DoAsyncOp1())
        .Then(x => DoAsynOp2())
        .Catch(e => Debugger.Log("Whoopsie!"));
}
private IPromise DoAsyncOp1()
{
    // If we throw an exception here, it will now be caught
}
private IPromise DoAsynOp2()
{
    // If we throw an exception here, it will also be caught
}
```

Or how would you structure your code? To be safe should you ALWAYS start every promise with ```Promise.Resolve()``` ?

Cheers,
Mike

**Comment by zsoi** [comment]
Technically, "DoAsyncOp1" does not DO an async op, it returns the promise for the result of an async op. So does DoAsyncOp2, but it is encapsulated in a promise resolution method and thus the promise resolver is responsible for the exception handling.
So if you want full error propagation through the promise chain, your proposal to start every promise chain with a "Promise.Resolve().Then(..)..." would be the way I'd do it, too.

**Comment by mikecann** [comment]
Hmmm, good point. I suppose you are right. It does still feel a little awkward still.

I wish Unity supported Async / Await!

**Comment by ashleydavis** [comment]
You can also do this:

private IPromise DownloadFile()
{​
    return new Promise((resolve, reject) => 
    {
          ... start an async operation, this can fail and will automatically reject the promise ...

          .... do the async operation and call resolve if it completes successfully ...
    });
}
