### ISSUE TITLE
iOS issue with UnhandledException handler

### ISSUE THREAD

**Issue by Renanse** [Real-Serious-Games/C-Sharp-Promise#2]
I know CSharpPromise has not been tested on iOS.  Here's one issue I hit (using the .dlls)

```
	void Awake() {
		Promise.UnhandledException += LogUnhandledException;
	}

	void LogUnhandledException(object sender, ExceptionEventArgs e)
	{
		Debug.LogErrorFormat("[NetworkManager] Promise had unhandled exception: {0} - {1}", sender, e.Exception);
		Debug.LogException(e.Exception);
	}
```

```
ExecutionEngineException: Attempting to JIT compile method '(wrapper managed-to-native) System.Threading.Interlocked:CompareExchange (System.EventHandler`1<RSG.ExceptionEventArgs>&,System.EventHandler`1<RSG.ExceptionEventArgs>,System.EventHandler`1<RSG.ExceptionEventArgs>)' while running with --aot-only.

  at RSG.Promise.add_UnhandledException (System.EventHandler`1 value) [0x00000] in <filename unknown>:0 
  at NetworkManager.Awake () [0x00000] in <filename unknown>:0 
```

I am on Unity5.1.3 and running on iOS 8

**Comment by Renanse** [comment]
fwiw, this goes away when using the latest source code (rather than precompiled dll).  Unfortunately, due to the nature of the AOT compiler in Unity, I am hitting AOT issues on iOS constantly.  I really like this library but seems it might need some big changes to work properly on iOS devices. :(

One example I hit:

```
ExecutionEngineException: Attempting to JIT compile method 'System.Collections.Generic.List`1<RSG.Promise`1/Handler`1<WyrmTale.JSON, WyrmTale.JSON>>:.ctor ()' while running with --aot-only.

  at RSG.Promise`1[WyrmTale.JSON].AddResolveHandler (System.Action`1 onResolved, IRejectable rejectable) [0x00000] in <filename unknown>:0 
  at RSG.Promise`1[WyrmTale.JSON].ActionHandlers (IRejectable resultPromise, System.Action`1 resolveHandler, System.Action`1 rejectHandler) [0x00000] in <filename unknown>:0 
  at RSG.Promise`1[WyrmTale.JSON].Then[JSON] (System.Func`2 onResolved, System.Action`1 onRejected) [0x00000] in <filename unknown>:0 
  at RSG.Promise`1[WyrmTale.JSON].Then[JSON] (System.Func`2 onResolved) [0x00000] in <filename unknown>:0 
```

triggered by a call from a LoadFromCloud("key").Then(...)  where LoadFromCloud returns IPromise<JSON>.

**Comment by ashleydavis** [comment]
We don't normally do iOS work, but one of the team has kindly agreed to bring is Mac in next week so we can test the promises library with xCode. Hopefully that will lead to some progress on this issue.

**Comment by Renanse** [comment]
That's pretty neat.  I guess it goes without saying that these are all runtime issues on device.

The first problem I run into is in debug. The Argument.NotNull<T> calls buried in the code all throw "ExecutionEngineException: Attempting to JIT compile method " errors at runtime when that method calls parameter.Compile().

**Comment by ashleydavis** [comment]
Is this ok now that I've integrated your PR?

**Comment by ashleydavis** [comment]
Please check out the latest version of library and let me know if this is still an issue.
