### ISSUE TITLE
Is .Done() equal to JS .finally()?

### ISSUE THREAD

**Issue by PhilippCh** [Real-Serious-Games/C-Sharp-Promise#22]
I've read through the source and don't think .Done(resolved, rejected) is equal to JavaScript's .finally(), is that correct? I know that .finally() is not officially in the spec, but almost all non-native Promise implementations offer the functionality and I think it'd be quite useful for game-development purposes as well.

In that case, would you mind adding a .Finally(Action) method? I'll see if I can create a pull request myself if it's not already on your agenda.

Best Regards
Philipp

**Comment by zsoi** [comment]
There is an open pull request for Finally() support: https://github.com/Real-Serious-Games/C-Sharp-Promise/pull/20

**Comment by ashleydavis** [comment]
Does anyone actually have a spec for how Finally should work?

**Comment by zsoi** [comment]
The bluebird library has some good explanation about the behavior (http://bluebirdjs.com/docs/api/finally.html).

Some core points:
1) Finally() should return a promise that is chained to the original promise
2) Finally() can not modify the value of the original promise (i.e. it cannot return a new value) BUT
3) Finally() can return a new promise, that is chained. When this chained promise fulfills, the value from that promise is discarded and the promise is fulfilled with the original promise value (see point 2). When the chained promise is rejected, than the original promise is rejected with that error. So Errors get propagated from Finally()-handlers, but values do not.

**Comment by RoryDungan** [comment]
See issue #30 on how done works and #29 regarding finally support.
