### ISSUE TITLE
Promise method is not thread safe.

### ISSUE THREAD

**Issue by LoranceChen** [Real-Serious-Games/C-Sharp-Promise#24]
hi, I'm use the tools for my Unity project, but encounter some exception seems about thread safe problem.
 A simple stage can reproduction it: 
Simulating 10000 times `Promise.Then<T>` method inner ThreadPool by `for` statement will throw some exception at `Promise<T>.InvokeResolveHandlers`'s `resolveCallbacks [i]` line (about at 326 lines), I have suffered **array out of index** and **object is null**.  
I think add some lock for `resolveCallbacks`, `resolveRejectables` and `rejectHandlers` is a good idea.

**Comment by zsoi** [comment]
Promises are meant to run in a single-process event loop, so supporting threads would mean to install event loops for every thread and not allow promises to cross thread borders. Of course client logic could defer computation onto a different thread and then resolve the promise in a way that it is resolved on the owning thread, not on the compute thread (e.g. look at C++ futures or C# async/await).

**Comment by LoranceChen** [comment]
I don't know how does c++ future deal with but scala will promise a Future's callback action is safe when add action or completing a Promise.Callback variable changes by a  `updateState` method,which is thread safe and in our situation the variable is `resolveCallbacks`, `resolveRejectables` and `rejectHandlers`, can ensure variable is thread safe.  
Handle at client logic will lose Promise expression power, a lot of logic code which not relative with actually works will be added anywhere.

Besides, does  `PromiseTimer` is the event loop but Promise? I'm not see loop on `Promise` yet or just mislead.

**Comment by zsoi** [comment]
PromiseTimer does provide kind-of a event loop. Promises come from the Javascript world which is inherently single-threaded and already provides the event loop from the standard library (setTimeout()). But this C# promise implementation does not have a built-in event loop and thus violates some of the A+ specifications (like unguaranteed asynchronous resolution - but that's just me citing the docs). The A+ specification for promises is even going so far that a single resolution step can occur in one tick (https://promisesaplus.com/#point-67). Implementing this for multiple threads would be a hell of deadlock and race condition potential. So maybe you're better off with message passing for inter-thread communication? As I said, "fulfilling" of the promise (whatever that may be - downloading a web site, computing pathfinding, ...) could be moved to threads pretty easily when it then schedules the resolution of the promise on the main thread via a mechnism like PromiseTimer provides. You'd just have to make PromiseTimer threadsafe and the rest should just work.

For a better understanding of this discussion, what is your actual use case?

**Comment by LoranceChen** [comment]
I'm try use Promise warp a asyc socket communicate which contains connection operation, send and wait a result in Promise. Obviously, the socket filling Promise under another thread rather then main thread.  
The really thread problem is when I want notice those Promise by multipurpose,such as do a log when connected and both show a tip "you have connected" on UI, these actions is under multi thread and I think log should be in another thread to deal with.

I have know the event loop means and you design. By the way, I already use `lock` keyworks to ensure Promise is thread safe, at least 10000 times calling `Then` is ok, by this:  
```
...
/// <summary>
/// Error handler.
/// </summary>
private Object rejectHandlersLock = new Object(); //add lock
private List<RejectHandler> rejectHandlers;

/// <summary>
/// Completed handlers that accept a value.
/// </summary>
private Object resolveLock = new Object(); //add lock
private List<Action<PromisedT>> resolveCallbacks;
private List<IRejectable> resolveRejectables;
...
```
locks used at `AddResolveHandler` method, `ClearHandlers` method, `InvokeResolveHandlers` method  ,etc,where callback variable set as left value.

**Comment by LiamKarlMitchell** [comment]
https://github.com/nickgravelyn/UnityToolbag
Future and Dispatcher
Wrap the result passed back to the promise.Resolve
