### ISSUE TITLE
NuGet package does not support .Net Portable project types.

### ISSUE THREAD

**Issue by yozepi** [Real-Serious-Games/C-Sharp-Promise#25]
Supporting .NetPortable project types would be extremely useful for developers seeking to create a single shared library that could run in both Android and iOS builds. This is becoming a common scenario when using Xamarin Forms.

**Comment by ashleydavis** [comment]
Is this the same as .NET core?

**Comment by RoryDungan** [comment]
PCLs have been [deprecated](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/#user-content-what-about-portable-class-libraries) in favour of .NET Standard, which is now supported in version 3.0.1.
