### ISSUE TITLE
Allow promises to be cancelled

### ISSUE THREAD

**Issue by meta-meta** [Real-Serious-Games/C-Sharp-Promise#27]
see:
https://github.com/facebook/react/issues/5465#issuecomment-157888325
https://github.com/tc39/proposal-cancelable-promises

use case: I want to use promises for animating state transitions of a UI element. I want to animate and then perform an action in a `Then()` when the transition completes, but if the user triggers a different state before this transition completes, switch to a new animation and reject the first promise.

**Comment by ashleydavis** [comment]
Thanks for the link to the proposed standard, it's going to be interesting to see if they actually include this in the JS standard.

Generally though promises are just not designed to be cancelled. We had the same problem with them... we ended up throwing an exception to terminate a promise chain, but it felt inelegant and clunky.

These days we tend to use [state machines](https://github.com/Real-Serious-Games/Fluent-State-Machine) or [behaviour trees](https://github.com/codecapers/Fluent-Behaviour-Tree) for operations that are cancellable or that can change dynamically and I'd encourage you to do the same.

Of course we still use promises extensively, typically we just use them for non-cancellable asynchronous operations.

**Comment by mouldi** [comment]
Thank you guys for RSG library

**Comment by meta-meta** [comment]
thanks @ashleydavis I'll give these a whirl!
