### ISSUE TITLE
Is there a "Always" callback?

### ISSUE THREAD

**Issue by nah0y** [Real-Serious-Games/C-Sharp-Promise#29]
Hello!

Quick question.
Is there a callback that is going to be called wether the "request" succeeded or not?

Let's say I'm starting a promise, and either it succeed or not, I want to call a specific method. And I don't want to have to call the method in "Then" and also in "Catch". Is there a way to do that?

Thanks!

**Comment by ashleydavis** [comment]
No there isn't an Always callback.

**Comment by nah0y** [comment]
Don't you think it's a good idea? :)

**Comment by ashleydavis** [comment]
Some of us have talked before about having a 'Finally' callback which sounds the same as what you want.

We haven't accepted many pull requests yet, sometimes we get them but they come with additional baggage. For example unnecessary formatting changes, other complex changes that are not needed or lack of unit tests.

If you can keep the code changes as simple as possible, make sure the code is fully covered by unit tests and there are no unnecessary changes then there is no reason why we wouldn't accept the change.

The change also has to be fully backward compatible. We rely on this library to work and not be broken.

So please feel free to contribute, we'll accept your pull request if makes the promise library and doesn't break anything.

**Comment by nah0y** [comment]
I've never had the chance to play with unit tests before, so I'll see what I can do :)
And I totally understand for poor pull requests, if I do this, I'll try to stick to the point without breaking or modifying things. Just adding the one callback.

**Comment by RoryDungan** [comment]
A "Finally" callback is not part of the A+ standard or ES6 promises, even though some JavaScript Promise libraries support it. How I've seen that functionality implemented before with ES6 promises is to simply chain another .Then after your .Catch, like example 1 on this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

I tested and this doesn't work with C-Sharp-Promise, but it does work in Q and Bluebird in JavaScript. Not sure what the A+ standard has to say regarding chaining a .Then after a failure callback though, since technically it doesn't even mandate that you have a .Catch method.

**Comment by RoryDungan** [comment]
Okay I just had a read of the spec and 2.2.7.1 _does_ specify that "if onRejected returns a value x, run the Promise Resolution Procedure", which matches up with a TODO in our tests (2.2.cs, line 334 - "Catch handler needs to be able to return a value."). 

If we want to fully support Promises/A+we should implement support for that, although at the moment we're pretty busy at RSG at the moment so I can't guarantee that we'll have time for it any time soon. Pull requests are welcome though.

**Comment by nah0y** [comment]
Thanks for your time!

Well, what happens if you call Then after Catch, and you have an exception thrown in the final Then? Do you also need another Catch? :)

But I guess it's the same thing when using Finally...

Anyway, even if it's not part of the A+ standard or ES6 promises as you said, I can only see this as a super super useful addition, as it's useful in a LOT of cases, it's not something isolated. But I think I'll try to do it when I can, even if it's for my own code :)
