### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by holycattle** [Real-Serious-Games/C-Sharp-Promise#3]
Hello! This is a great library; thank you for sharing it with everyone.

I'm curious though -- have you guys tested this for mobile games? How is the performance? I haven't tried this library yet, but I imagine that this would take a toll on the GC?

Thanks!

**Comment by ashleydavis** [comment]
Our first application to extensively use promises is a Unity app that runs on Android. Our app is quite performance sensitive in that any degradation in performance would cause a bad user experience, something we don't want. 

We haven't seen any performance problems relating to the use of this promise library.

However the promise library can generate a lot of memory allocation depending on how often you use it. Whether this causes you a performance problem or not depends on where you use it and how often you use it and how powerful your mobile hardware is.

I can't make any promises on what the performance will be like for you. But I'd love to hear about your experience should you chose to use it. If it causes you performance problems then maybe we can work together to improve the library.

**Comment by holycattle** [comment]
Thanks for the quick reply! I'll try to benchmark this over the week.
