### ISSUE TITLE
How to keep the "same" promise when chained?

### ISSUE THREAD

**Issue by nah0y** [Real-Serious-Games/C-Sharp-Promise#41]
Hey guys :)

I just stumbled upon a small issue.
I'm using the code below:

```
public static IPromise<ProcessResult> ChmodAndExecute(string filePath)
{
	Promise<ProcessResult> promise = new Promise<ProcessResult>();

	ExecuteProcess("chmod", "+x \"" + filePath + "\"")
	.Then(processResult => 
	{
		return ExecuteProcess(filePath);
	})
	.Catch(exception =>
	{
		promise.Reject(exception);
	});

	return promise;
}
```

And calling it using:
```
ProcessUtils.ChmodAndExecute(serverPath)
.Then((ProcessUtils.ProcessResult processResult) => 
{
	// Do something here
})
.Catch(exception =>
{
	// ...
});
```

The thing is that, I never enter inside the // Do something here.
It's because I'm using return ExecuteProcess(filePathWithArguments); in the ChmodAndExecute method, and inside this ExecuteProcess method, I create ANOTHER promise.

One way I fixed it is by passing the already existing promise to my ExecuteProcess method, doing return ExecuteProcess(promise, filePathWithArguments); like below
```
public static IPromise<ProcessResult> ChmodAndExecute(string filePath)
{
	Promise<ProcessResult> promise = new Promise<ProcessResult>();

	ExecuteProcess("chmod", "+x \"" + filePath + "\"")
	.Then(processResult => 
	{
		return ExecuteProcess(promise, filePath);
	})
	.Catch(exception =>
	{
		promise.Reject(exception);
	});

	return promise;
}
```

But my question is... can I cast this ExecuteProcess method to my already created promise?
Doing something like:
promise = (Promise<ProcessResult>)ExecuteProcess(filePath); ?
which would give the following code:
```
public static IPromise<ProcessResult> ChmodAndExecute(string filePath)
{
	Promise<ProcessResult> promise = new Promise<ProcessResult>();

	ExecuteProcess("chmod", "+x \"" + filePath + "\"")
	.Then(processResult => 
	{
		promise = (Promise<ProcessResult>)ExecuteProcess(filePath);
		return promise;
	})
	.Catch(exception =>
	{
		promise.Reject(exception);
	});

	return promise;
}
```

I tried, but it still does not work :/
PS: Yes, my ExecuteProcess creates a new promise, but also returns it. So if I cast the result of ExecuteProcess, I should now have the new promise inside the promise variable...

Let me know if this is not clear, and thanks in advance!

Yohan

**Comment by zsoi** [comment]
First, what you're doing, is one of the [antipatterns ](http://bluebirdjs.com/docs/anti-patterns.html) of promises! Just return the promise chain you already have:

```
public static IPromise<ProcessResult> ChmodAndExecute(string filePath)
{
	return ExecuteProcess("chmod", "+x \"" + filePath + "\"")
	.Then<ProcessResult>(processResult => 
	{
		return ExecuteProcess(filePath);
	});
}
```

All the error handling can be done by the caller of `ChmodAndExecute()`, and the returned promise will have the final process result as the resolution value.
I haven't checked the code with a compiler, but from my experience it should work. Should you run into any problems let me know (type resolutions and conversion can be tricky from time to time).

**Comment by nah0y** [comment]
Thanks :)
I should try that this Friday and let you know!
