### ISSUE TITLE
Possible issue when using PomiseTimer.WaitUntil for chains of identical user input

### ISSUE THREAD

**Issue by mjholtzem** [Real-Serious-Games/C-Sharp-Promise#42]
Just started messing around with this library and I believe I have encountered a bug. It's also possible that I am simply misusing the PromiseTimer class.

I have a function that waits for a specified key input from the user and then returns a string
```
private IPromise<string> WaitForKey(KeyCode inKey)
	{
		Promise<string> promise = new Promise<string>();

		pTimer.WaitUntil(_ => Input.GetKeyDown(inKey))
			.Then(() => promise.Resolve("I just pressed " + inKey.ToString()));

		return promise;
	}
```

This works as expected as long as I chain together different inputs. but if I ask for the same input twice in a row, they both resolve in the same frame. In the example below all three logs would occur after pressing spacebar a single time.
```
WaitForKey(KeyCode.Space)
			.Then(result => Debug.Log(result))
			.Then(result => WaitForKey(KeyCode.Space))
			.Then(result => Debug.Log(result))
			.Then(result => Debug.Log("We are all done taking input!!!"));
```
Is this expected behaviour? If so what would be the proper approach to this example?

**Comment by adamsingle** [comment]
An excellent question. This is indeed expected behaviour since the chain would resolve the first promise, move to the next one in the same "update" and check that same condition, which would still be true. There are probably a few ways to resolve this issue but one that comes to mind would be something like this:
	//on a side note, I'd probably call this something like WaitForKeyDown to be clearer
	private IPromise<string> WaitForKey(KeyCode inKey)
	{
		Promise<string> promise = new Promise<string>();


		Promise keyDownPromise = new Promise();
		if (Input.GetKey(inKey))
		{
			keyDownPromise = promiseTimer.WaitUntil(_ => Input.GetKeyUp(inKey));
		}
		else
		{
			keyDownPromise.Resolve();
		}

		keyDownPromise.
			.Then(() => promiseTimer.WaitUntil(_ => Input.GetKeyDown(inKey))
			.Then(() => promise.Resolve("I just pressed " + inKey.ToString()))
			.Done();
	
		return promise;
	}

This will wait for the keyup condition if the key is currently being held down when the function is called.
I hope that helps

**Comment by mjholtzem** [comment]
Cool thanks that makes sense

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
