### ISSUE TITLE
For Xamarin Forms?

### ISSUE THREAD

**Issue by lolohouse** [Real-Serious-Games/C-Sharp-Promise#43]
Hi, I am trying to use your library in a Xamarin forms application but it does not allow me to add it to a PCL project.
There is no way to use it in this environment?
Thank you

**Comment by adamsingle** [comment]
There shouldn't be any issues with adding it to a PCL. Can you share the errors Xamarin is throwing please?

**Comment by lolohouse** [comment]
hi, this error:

Could not install package 'RSG.Promise 1.2.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by adamsingle** [comment]
RSG.Promises is built to work with Unity projects, which are limited to .NET 3.5. It won't build into a project that is higher than that. Yours is set to .NET 4.5

**Comment by ashleydavis** [comment]
The code should work with with .NET 4.5, just not the existing projects. Feel free to recreate the project yourself and then you should be able to use it.

**Comment by adamsingle** [comment]
of course it should. What am I talking about? Shouldn't answer questions first thing in the morning after no sleep. Sorry lolohouse.

**Comment by lolohouse** [comment]
I have created a PCL library for .net framework 5.5 (profile111) and compiled it perfectly. I just had to change the ApplicationException class by Exception and everything perfect.
You could create a PCL .net 4.5 library and link classes, so it would be compatible with xamarin
Thank you and forgive my English which is not very good

**Comment by RoryDungan** [comment]
The latest version of the library no longer uses ApplicationException anywhere so the source should be fully compatible now.

If you'd like to set the project up to also build a library compatible with Xamarin forms we'd be happy to merge it and include that in future releases on Nuget, provided that it doesn't intefere with the .NET 3.5 build.
