### ISSUE TITLE
Include an example to support Callbacks and promises at the same time

### ISSUE THREAD

**Issue by jdnichollsc** [Real-Serious-Games/C-Sharp-Promise#44]
Hi guys,

Thanks for this library, it's amazing! Please, add an example into the **README** to support callbacks and promises at the same time, example: https://twitter.com/jdnichollsc/status/907695530758864896

Thanks in advance, Nicholls

**Comment by jdnichollsc** [comment]
Example
```
public IPromise<T> Get<T>(string url, Action<Exception, T> callback = null){
  var promise = new Promise<T>();
  AsyncOperation<T>(url, (err, res) => {
    if(err != null){
      promise.Reject(err);
    }
    else{
      promise.Resolve(res);
    }
    if(callback != null) callback(err, res);
  });
}
```

**Comment by RoryDungan** [comment]
Hey!

I can see how that could be useful, but is there a reason your example has a function that can both be passed a callback and return a promise as opposed to just overloading the function and providing two implementations? 

Having a single method that contains two code paths to work in two different ways is generally not a good practice in C#. If you want your API to be able to be used with both promises and callbacks, you should be able to accomplish the same thing with overloaded methods like this:
```
// Method returning a promise
public IPromise<T> Get<T>(string url) 
{
    var promise = new Promise<T>();
    AsyncOperation<T>(url, (err, res) => {
        if (err != null)
        {
            promise.Reject(err);
        }
        else
        {
            promise.Resolve(res);
        }
    });
    return promise;
}

// Method that lets us use a callback
public void Get<T>(string url, Action<Exception, T> callback)
{
    Get(url)
        .Then(value => callback(null, value))
        .Catch(ex => callback(ex, null));
}
```

The functionality for that code example is demonstrated in the [Creating a promise for an Async operation](https://github.com/Real-Serious-Games/C-Sharp-Promise#creating-a-promise-for-an-async-operation) and [Waiting for an Async operation to complete](https://github.com/Real-Serious-Games/C-Sharp-Promise#waiting-for-an-async-operation-to-complete) examples. Let me know if there's a reason that doesn't work for your use case or you think there's a way we could improve the documentation to be more clear though.

**Comment by jdnichollsc** [comment]
@RoryDungan No, I think that the documentation is excellent, I congratulate you for your great work!

I mean like JS with a lot of APIs that support promises and callbacks at the same time, for example http://slides.com/juandavidnicholls/promises#/3 Maybe it's a good option if you want to reuse the code and have only one method that support both, but is an excellent option with overloaded methods.

Again, I congratulate you on this brilliant idea!

Regards, Nicholls
