### ISSUE TITLE
Add RestClient sample

### ISSUE THREAD

**Issue by jdnichollsc** [Real-Serious-Games/C-Sharp-Promise#46]
Hi guys,
What do you think about my first Unity script based on Promises? If you want you can add my sample in your README
https://github.com/proyecto26/RestClient 

Regards, Nicholls

**Comment by ashleydavis** [comment]
Thanks Nicholls, looks good!

Please fork the promise library, add what you want to the README and submit a pull request. If it looks appropriate and helpful to our users we'll accept it!
