### ISSUE TITLE
Exception handling not consistent with A+

### ISSUE THREAD

**Issue by Nepoxx** [Real-Serious-Games/C-Sharp-Promise#51]
Consider the following JavaScript code:

```javascript
const Promise = require('bluebird'); // Using native promises does not change the behavior

Promise.resolve()
  .then(() => {
    console.log('then1');
    throw new Error('Foo');
  })
  .catch(() => {
    console.log('catch');
  })
  .then(() => {
    console.log('then2');
  })
```

The output:
```
then1
catch
then2
```

Now, using RSG promises:

```c#
void Start () {
	 Promise.Resolved()
            .Then(() => {
                Debug.Log("Then1");
                throw new NotImplementedException("NO!");
            })
            .Catch((e) => {
		Debug.Log("Catch");
	    });
	    .Then(() => {
		Debug.Log("Then2");
            });
}
```

The output:
```
then1
catch
```

(Using v1.2.2)

Corresponding A+ spec rule: https://promisesaplus.com/#point-41

> If either onFulfilled or onRejected returns a value x, run the Promise Resolution Procedure [[Resolve]](promise2, x).

**Comment by philippevk** [comment]
Should be something like that I think:
``` C#
public IPromise<PromisedT> Catch(Action<Exception> onRejected)
{
    var resultPromise = new Promise<PromisedT>();
    resultPromise.WithName(Name);

    Action<PromisedT> resolveHandler = v =>
    {
        resultPromise.Resolve(v);
    };

    Action<Exception> rejectHandler = ex =>
    {
        onRejected(ex);
        resultPromise.Resolve(default(PromisedT));
    };

    ActionHandlers(resultPromise, resolveHandler, rejectHandler);

    return resultPromise;
}

public IPromise<ConvertedT> Catch<ConvertedT>(Func<Exception, ConvertedT> onRejected)
{
    var resultPromise = new Promise<PromisedT>();
    resultPromise.WithName(Name);

    Action<PromisedT> resolveHandler = v =>
    {
        resultPromise.Resolve(v);
    };

    Action<Exception> rejectHandler = ex =>
    {
        resultPromise.Resolve(onRejected(onRejected));
    };

    ActionHandlers(resultPromise, resolveHandler, rejectHandler);

    return resultPromise;
}
```

**Comment by RoryDungan** [comment]
Good catch. This is related to the issue where catch handlers can't return a value. For example, the following code will output "blah" with Javascript ES6 promises: 

```js
new Promise((res, rej) => rej())
    .catch(_ => 'blah')
    .then(console.log)
```

The same thing with RSG promises will fail because `.Catch` expects an `Action<Exception>`, where it would need to support a `Func<Exception, PromisedT>` as well to return a value. 

I'll try out that code you posed in your second comment and see if we can incorporate it into the library. For now though I think you should be able to get the functionality you want of running another callback after `.Catch` by using `.Finally` instead of `.Then`:

```cs
void Start () {
	 Promise.Resolved()
            .Then(() => {
                Debug.Log("Then1");
                throw new NotImplementedException("NO!");
            })
            .Catch((e) => {
		Debug.Log("Catch");
	    });
	    .Finally(() => {
		Debug.Log("Then2");
            });
}
```

**Comment by RoryDungan** [comment]
Okay that was actually pretty simple to implement so I've made a pull request with the new functionality (#52) so that the other maintainers have a chance to have a look at it before it's merged. Will close this issue once that gets resolved.

**Comment by RoryDungan** [comment]
This has been merged now. Since the logic works in a different way to before, I also bumped the version number to 2.0 to ensure it doesn't break existing projects.
