### ISSUE TITLE
How does a Promise return control to Unity?

### ISSUE THREAD

**Issue by frost-byte** [Real-Serious-Games/C-Sharp-Promise#59]
One thing I'm confused about is returning control to Unity after calling a Promise that initiates a coroutine.

I would like my app to remain responsive while I perform a sequence of Promises that are encapsulated within a Coroutine, because the app's UI needs to update an element to indicate the progress of these operations.

Is it possible (or is this a good use case) for  RSG.Promises ?
I'm not sure how to proceed, and any input you can provide would be greatly appreciated!

**Comment by RoryDungan** [comment]
I think I'd need to see an example to get exactly what you mean by returning control to Unity, but I think that [chaining another promise](https://github.com/Real-Serious-Games/C-Sharp-Promise#chaining-async-operations) using `.Then` would do what you need. The ability to chain actions after a promise is one of the main advantages of promises over Unity coroutines, which have no built-in mechanism to manage sequences of tasks. If you're looking for the Promise equivilant to `yield return null` in a Unity coroutine then the [PromiseTimer](https://github.com/Real-Serious-Games/C-Sharp-Promise#promisetimer-class) class will probably do what you need. 

In regards to making your UI responsive, it's important to remember that neither promises or coroutines necessarily run in a separate thread so just putting code inside a promise or coroutine won't always improve your framerate if the code runs synchronously anyway. Promises are intented as a way to *manage* any kind of asynchronous code, for instance something running in a separate thread, asynchronous IO like an HTTP request, or a task that happens over several frames. Check out this blog post for more details: http://www.what-could-possibly-go-wrong.com/threads-promises-and-unity/

**Comment by frost-byte** [comment]
I have a UI Element in Unity that I use to show the progress of a coroutine wrapped inside a promise.  The following code, contained within the primary script of my App (a Monobehaviour), is a rough outline of how I'm using RSG.Promises
```csharp
public void OnLoadMesh(){
      // FileBrowser presented to user and path to file selected by user (pseudocode)
      string fileName = OpenFilePanel();

      LoadMesh(myMesh, fileName).Then(mesh => OnMeshLoaded();
}
```
```csharp
private IPromise<MyMeshType> LoadMesh(MyMeshType mesh, string fileName){
    return MyMeshType.Load(mesh, fileName);
}

private void OnMeshLoaded(){
    // pseudocode
    EnableMeshUI();
    AssignMyMeshToGameObject();
}
```
The code in the MyMeshType Loader class follows the example in your [AssetBundleLoader](https://github.com/Real-Serious-Games/Unity-Async-and-Promises/blob/1a29ef271c42fa4d2581f2862f47ebbb63b2557f/Assets/6.%20AssetBundleLoader/AssetBundleLoader.cs).

In my previous implementation, without promises, I was able to enumerate over a similar coroutine (which contained nested enumerators/coroutines). This would allow Unity to continue to update my UI element. You can see examples of iteration over a nested Coroutine here [Coroutine and Iterator Function Tricks](https://jacksondunstan.com/articles/3036)

```csharp
IEnumerator RandomElements(int[] array, int num)
{
    if (array == null)
    {
        yield break;
    }
 
    var random = new Random();
    for (var i = 0; i < num; ++i)
    {
        var index = random.Next(array.Length);
        yield return array[index];
    }
}
```
However, it appears that I'm supposed to only yield one time before resolving or rejecting (Based upon several tutorials using your library.) Using this approach I can not enumerate/yield multiple times using the coroutine to let unity update the UI element. (I know coroutines/yield really aren't true asynch methods, just a way of performing a number of iterations each frame)

As a side note, I did see the PromiseTimer that you mention, however I did not think its intent was to perform a subset of code within a promise before yielding.

So, what I really need is a way of communicating between the async operation within the Promise and my Unity application.  (The entire process can take several minutes, because I'm doing more than just loading a mesh) For the moment, I'm researching how I might send an event to the UI element.

**Comment by RoryDungan** [comment]
Thanks for that example, I think I get what you're trying to do now. Essentially how coroutines work is that calling `StartCoroutine` registers your `IEnumerator` function with Unity so that it has `MoveNext()` called on it every subsequent `Update()` loop until it has finished. Promises are not necessarily linked to the Unity `Update()` loop since they can resolve at any point, but the [PromiseTimer](https://github.com/Real-Serious-Games/C-Sharp-Promise#promisetimer-class) was made to deal with situations where we do want promises with a callback that is called every `Update()` cycle. 

PromiseTimer.WaitUntil and WaitWhile give us a callback that is called every update, which lets you do some work every frame until the task is done. This is still a little different from coroutines because the whole of the callback function is run rather than just the section from the last `yield return`, but you should still be able to use it to achieve the same result.

Here's an example similar to your RandomElements coroutine one that logs a random element of the supplied array every update:
```cs
IPromise RandomElements(int[] array, int num)
{
    if (array == null)
    {
        return Promise.Rejected(new ArgumentNullException("array"));
    }
 
    var random = new Random();
    var i = 0;
    return promiseTimer.WaitWhile(_ => {
        var index = random.Next(array.Length);
        Debug.Log(array[index]);

        return i++ < num;
    });
}
```
