### ISSUE TITLE
Incorrect overloads of .Then and .Catch

### ISSUE THREAD

**Issue by RoryDungan** [Real-Serious-Games/C-Sharp-Promise#61]
There are currently 3 overloads of `Promise<T>.Then` that don't make sense and 1 of `Promise.Then`:
```cs
interface IPromise<PromisedT>
{
    // These should be changed to return a non-generic promise because the callbacks don't 
    // return a value
    IPromise<PromisedT> Then(Action<PromisedT> onResolved, Action<Exception> onRejected);
    IPromise<PromisedT> Then(Action<PromisedT> onResolved);

    // This should be changed to return IPromise<ConvertedT> to be more flexible.
    // Changing to ConvertedT would retain backwards compatibility because ConvertedT can be
    // the same as PromisedT
    // IPromise<PromisedT> Catch(Func<Exception, PromisedT> onRejected);
    // EDIT: this actually doesn't work - see below
}

interface IPromise
{
    // Now that onRejected handlers can return values, this no longer makes sense. The second
    // argument should be type 'Func<Exception, ConvertedT>' or 'Func<Exception, IPromise<ConvertedT>>'
    IPromise<ConvertedT> Then<ConvertedT>(Func<IPromise<ConvertedT>> onResolved, Action<Exception> onRejected);
}
```

These should be modified to fit the rest of the library or just removed. 

In addition, there are many helpful overloads of `.Then` and `.Catch` that we could add to support use in a more similar way to JS Promises:

```cs
// Generic promise
IPromise<ConvertedT> Then(Func<PromisedT, ConvertedT> onResolved, Func<Exception, ConvertedT> onRejected);
IPromise<ConvertedT> Then(Func<PromisedT, IPromise<ConvertedT>> onResolved, Func<Exception, ConvertedT> onRejected);
IPromise<ConvertedT> Then(Func<PromisedT, ConvertedT> onResolved, Func<Exception, IPromise<ConvertedT>> onRejected);
IPromise<PromisedT> Catch(Func<Exception, IPromise<PromisedT>> onRejected);
IPromise Then(Action<PromisedT> onResolved);
IPromise Then(Action<PromisedT> onResolved, Action<Exception> onRejected);
IPromise Then(Action<PromisedT> onResolved, Func<Exception, IPromise> onRejected);
IPromise Then(Func<PromisedT, IPromise> onResolved, Func<Exception, IPromise> onRejected);
IPromise Catch(Func<Exception, IPromise> onRejected);

// Non-generic promise
IPromise<ConvertedT> Then(Func<ConvertedT> onResolved);
IPromise<ConvertedT> Then(Func<ConvertedT> onResolved, Func<Exception, ConvertedT> onRejected);
IPromise<ConvertedT> Then(Func<IPromise<ConvertedT>> onResolved, Func<Exception, ConvertedT> onRejected);
IPromise<ConvertedT> Then(Func<ConvertedT> onResolved, Func<Exception, IPromise<ConvertedT>> onRejected);
IPromise<ConvertedT> Then(Func<IPromise<ConvertedT>> onResolved, Func<Exception, IPromise<ConvertedT>> onRejected);
IPromise Then(Action onResolved, Func<Exception, IPromise> onRejected);
IPromise Then(Func<IPromise> onResolved, Func<Exception, IPromise> onRejected);
IPromise Catch(Func<Exception, IPromise> onRejected);
```

Most of these could be implemented quite easily by simply making them call through to the existing methods.

**Comment by ashleydavis** [comment]
Sounds good, just be careful not to break existing code.

**Comment by sindrijo** [comment]
During the weekend I ran into some problems with this breaking tests and realizing some of them not being compatible with the spec, specifically the 'conversion' _thens_ that return `IPromise<TConverted>` or `IPromise` from `TPromised`.

> 2.27 then must return a promise [3.3].
` promise2 = promise1.then(onFulfilled, onRejected);`
>2.2.7.3. If onFulfilled is not a function and promise1 is fulfilled, promise2 must be fulfilled with the same value as promise1.

> 2.27 then must return a promise [3.3].
` promise2 = promise1.then(onFulfilled, onRejected);`
>2.2.7.3. If onFulfilled is not a function and promise1 is fulfilled, promise2 must be fulfilled with the same value as promise1.

Also the current implementation of IPromise<ConvertedT> Then(Func<ConvertedT> onResolved, [...]) seems to violate the first rule of the 'then' method spec:
> 2.2.1 Both onFulfilled and onRejected are optional arguments

Because it is a 'conversion' and thus it is not optional, because it potentially the only 'link' in the chain that has knowledge of how to do the conversion. In other words we could define an extension to the spec like this: 

> 2.2.1.3 If onFulfilled would be a conversion then it is not optional
> 2.2.1.4 If onRejected would be a conversion then it is not optional

Alternatively we could rename these 'conversion' methods to something else like 'ThenSelect' to indicate that it is not part of the implementation of the A+ spec.

We should probably take a closer look at defining and documenting exceptions/differences this library has/should have to the A+ spec?

**Comment by RoryDungan** [comment]
You're right that the way we handle optional arguments isn't entirely consistent with the A+ standard, but we decided it was a worthwhile tradeoff because of the way the C# type system works.

In JS promises, you can return a completely different type of object in a regular ".Then" callback, so I think that for ease of use, there are a lot of benifits to having the C# promises behave the same way. This feature is very widely used but isn't mentioned in the A+ standard because JS is a dynamically-typed language so has it for free anyway.

The issue you're talking about stems from the fact that the return type of a JS function can be anything, whereas in C# unless we return a very generic type like `object`, it needs to be determined at compile time. Returning an `object` isn't really a good option because it forces you to do a lot of ugly type-casting, and looses the type safety of the current approach that uses generics.

We decided that for most of our use-cases, having `Then` allow you to convert between different types was more useful than supporting optional arguments, since it is also usually neater to call `promise1.Catch(ex => ...)` than `promise1.Then(null, ex => ...)` anyway. `Catch` isn't part of the A+ standard but has been implemented by all major A+ compliant promise libraries like Bluebird and Q, and is part of the ES6 promise standard. 

These days we aim to be compatible with ES6 promises rather than A+ promises beause they are what most people will be using in JS land, and are a superset of A+ promises anyway.

**Comment by RoryDungan** [comment]
Turns out we can't change `IPromise<PromisedT> Catch(Func<Exception, PromisedT> onRejected);` to `IPromise<ConvertedT> Catch<ConvertedT>(Func<Exception, ConvertedT> onRejected);` like I'd originally planned because, while the onRejected handler can convert to a different type of promise, we have to support the case where the onRejected handler *wasn't* called as well. 

This means if we're using an onRejected that converts the promise type, we must also have an onResolved that converts the promise type at the same time.

**Comment by RoryDungan** [comment]
The incorrect overloads have been changed in v3.0.0. Other potentially useful ones can be added to a future release if necessary and they don't cause any other issues.
