### ISSUE TITLE
Benefit of calling both Catch() and Done()?

### ISSUE THREAD

**Issue by atraver** [Real-Serious-Games/C-Sharp-Promise#63]
This isn't so much an issue as a general question (sorry if there's a better place to put this, I wasn't sure). I notice that in examples 3, 4, and 5, you do the following pattern:

```
SomePromise
  .Then(() => {})
  .Catch(e => {})
  .Done();
```

Is there a benefit to calling both `Catch` and `Done` in these cases? I can see recovering from an exception in `Catch` and calling another `Then`, but the `Done` seems redundant.

Am I missing something?

**Comment by RoryDungan** [comment]
It's generally good practice to terminate your chain with a .Done() call in case an exception is thrown inside the Catch handler. 

Here's an example:
```cs
// This will silently fail
SomePromise
    .Then(() => {})
    .Catch(e -> throw new Exception());
```
If there had been a .Done() on the end, the exception would still be sent to the unhandled exception handler.

**Comment by atraver** [comment]
Aah, good point. Thanks for the quick response, and the fantastic library! It's helped me immensely with reasoning about otherwise gnarly `Update` methods and sequential, asynchronous events (e.g., bootstrapping/loading our game).
