### ISSUE TITLE
Promise<T>.All should not use value returning catch

### ISSUE THREAD

**Issue by sindrijo** [Real-Serious-Games/C-Sharp-Promise#67]
Now that we have IPromise Catch(Action<Exception> on IPromise<T> the static All method should us the non-value version of Catch to avoid the ugly `return default(PromisedT)`

**Comment by RoryDungan** [comment]
Good point. I think this would work by just deleting that `return default(PromisedT);` line. Can't see how that would break any existing code, so unless there's anything else you think would be worth changing I'll switch it over. 👍

**Comment by sindrijo** [comment]
Yes, I can't see how it would break anything either.

**Comment by RoryDungan** [comment]
I've fixed this now.
