### ISSUE TITLE
"Resolve" a promise multiple times

### ISSUE THREAD

**Issue by nah0y** [Real-Serious-Games/C-Sharp-Promise#69]
Hello again,

Is there to "resolve" a promise multiple times?
Imagine I'm scanning for bluetooth devices, and I use a Promise for that.
I would like to call .Resolve(deviceAddress) every time a new address is found for example, and start another process that will reject the promise after 60sc (to stop scanning).
I don't think there's a way to do that, right?

**Comment by sindrijo** [comment]
> Is there to "resolve" a promise multiple times?

No, that kind of goes against the idea of a _Promise_, you should be using an event/callback or message pattern.

**Comment by ashleydavis** [comment]
You should be using reactive extensions for that (rx), that's an implementation of asynchronous streaming. 

Where a promise is an asynchronous delivery mechanism for a single result, rx is an asynchronous delivery mechanism for a continuous stream of results.

I recommend reading the book into to rx, is free online.

**Comment by nah0y** [comment]
Thanks to both of you for your answers. That's what I thought (and I'm currently using event/callbacks), but thanks for the tip with rx!

**Comment by ashleydavis** [comment]
Here's a link to the book: http://www.introtorx.com/

If you like it please buy it to support the author.

Also more generally you should google 'reactive programming'.  It's a really interesting concept that a lot of people are experimenting with.

**Comment by nah0y** [comment]
Yes, I see that a lot recently. I have to find some time to dig into it though :(
