### ISSUE TITLE
Rejecting a promise that is not of type System.Exception

### ISSUE THREAD

**Issue by mattbadley** [Real-Serious-Games/C-Sharp-Promise#82]
I'm trying to integrate this library with PlayFab (a cloud based games backend).  I have it working except for the error side of things.

Here's some code:

```javascript
public IPromise<LoginResult> Login()
{
	var promise = new Promise<LoginResult>();

	var request = new LoginWithIOSDeviceIDRequest();
			
	PlayFabClientAPI.LoginWithIOSDeviceID(request, (LoginResult result) => promise.Resolve(result) , (PlayFabError error) => promise.Reject(new System.Exception()));

	return promise;
}
```

I then setup the promise chain in the following way -

```javascript
Login()
	.Then(result => {
		PlayFabId = result.PlayFabId;
	})
	.Catch(error =>
		Debug.Log("An exception occured while loging in! " + error)
	);
```

The problem is with promise.Reject.  I can only pass in an object which is of type System.Exception... but Playfab returns errors of type PlayFabError. 

How can I set this up to use PlayFabError objects?

Also I've put the lambda functions inline (the success and fail callbacks), but this doesn't feel right.  Is there a better way to format this?

Any help would be appreciated!

**Comment by nah0y** [comment]
Hello,

Does PlayFabError extends System.Exception? If yes, then I think you should be able to use it.
If not, maybe you need to create your own class that extends System.Exception and contains a PlayFabError variable?

**Comment by mattbadley** [comment]
Thanks for the comments - wrapping the PlayFabError in my own custom class was a good solution and works well!
