### ISSUE TITLE
Need implicit casts between Promise<object> and Promise and interfaces

### ISSUE THREAD

**Issue by ericnewton76** [Real-Serious-Games/C-Sharp-Promise#93]
Need some implicit casts for T=object scenarios.  I keep running into odd compiler errors of not able to convert from Promise<object> to Promise which returns an object... lol

I'd like to start the discussion at least.  I'm trying ponder this for a bit, as I'm trying to use this library in a non-unity scenario, but realistically I really love the idea.  I believe JS got async programming correct with Promises, and C# team got async wrong with their Task<object> async await mentality. (Granted the await is coming to JS which is good too)

**Comment by ericnewton76** [comment]
Just to clarify after thinking about this.

All Promises should still shuttle around an object reference, and that object ref can be null.

So a `Then((x) => { Assert.That(x==null) })` on a `Promise<object>` cast from a `Promise`.  This should work fine, given the following:

```c#
var Promise1 = new Promise((resolve,reject) => { resolve(); });
var Promise2 = new Promise<object>((resolve,reject) => { resolve("A"); });

Promise.All(Promise1,Promise2)
.Then(results => {
  Assert.That(results.ElementAt(0), Is.Null);
  Assert.That(results.ElementAt(1), Is.NotNull);
  Assert.That(results.ElementAt(1), Is.EqualTo("A"));
}
```

**Comment by ericnewton76** [comment]
Just a question, was there a need for the IPromise interfaces?  I dont actually see a need for them.

That way, `Promise.All` takes `Promise` types instead, and the implicit casts can easily shuttle Promise<object> to Promise due to baseclass 

```c#
public static Promise Promise.All(params Promise[] promises)
```

**Comment by ashleydavis** [comment]
It doesn't feel right to me that a promise that yields no value should be able to implicitly cast to a null result.

There are two reasons for the interfaces. 
1. Having an interface allows a promise to be locked.
2. Having two interfaces allows you to seperate your concerns. One interface allows a promise to be awaited, the other allows a lifetime to be resolved.
