### ISSUE TITLE
Promise Queue?

### ISSUE THREAD

**Issue by tmilker** [Real-Serious-Games/C-Sharp-Promise#96]
Is it possible to build a promise queue like http://erictrinh.com/posts/promise-queues ?  Any examples?

I've been using this library for my game and it has worked great but I'm communicating with a Bluetooth device it would be useful if my promises could wait for other, on-going promises to finish before new commands are issued(through promises).  I don't see anything in the documentation about chaining multiple promises that aren't all connected at one call location.  Is that even possible with this?

**Comment by ashleydavis** [comment]
Check out the section on `Promise.sequence` in [my article](https://www.what-could-possibly-go-wrong.com/promises-for-game-development/). It could be what you are looking for.

**Comment by tmilker** [comment]
Thanks.  I'll have to do some thinking about how I could integrate that.
